apiVersion: v1
kind: Pod
metadata:
  name: ansible-master
spec:
  containers:
    - name: master
      image: ansible-node
      imagePullPolicy: Never
      ports:
        - containerPort: 22
      securityContext:
        privileged: true